[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "battery-tray"
version = "0.1.0"
description = "Tray utility to manage battery charge thresholds"
authors = [
    { name="Max S", email="" },
]
dependencies = [

]
requires-python = ">=3.8"
